version: "3.2"
services:
  php:
    build:
      context: .
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    environment:
      - DBNAME=api-weather
      - DBUSER=root
      - DBPASS=123
    container_name: treinamento-php
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=api-weather
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql-volume:/var/lib/mysql
    container_name: treinamento-mysql
networks:
  backend:
volumes:
  mysql-volume:
